/**
 * Application Submission API
 *
 * POST /api/applications/submit
 * Submit a new equipment finance application
 */

import { NextRequest, NextResponse } from 'next/server';
import { transaction } from '@/lib/db';
import { ApplicationStatus } from '@/types/database.types';

// =====================================================
// Request/Response Types
// =====================================================

interface ApplicationSubmitRequest {
  // Business details
  abn?: string;
  tradingName?: string;
  businessName?: string;
  entityType?: string;
  businessAddress?: {
    street: string;
    city: string;
    state: string;
    postcode: string;
  };

  // Applicant details
  applicantFirstName?: string;
  applicantLastName?: string;
  applicantEmail?: string;
  applicantPhone?: string;
  applicantDateOfBirth?: string;
  residencyStatus?: string;
  residentialAddress?: {
    street: string;
    city: string;
    state: string;
    postcode: string;
  };

  // Financial position
  assets?: {
    homeValue?: number;
    investmentPropertyValue?: number;
    cashAtBank?: number;
    vehiclesValue?: number;
    homeContentsValue?: number;
    investmentsSharesValue?: number;
    otherAssetsValue?: number;
  };
  liabilities?: {
    mortgageHome?: number;
    mortgageInvestment?: number;
    vehicleLoan?: number;
    creditCards?: number;
    otherLiabilities?: number;
  };

  // Finance details (optional - may be added later)
  financeProduct?: string;
  invoiceAmount?: number;
  termMonths?: number;
  monthlyPayment?: number;
  annualRate?: number;
}

interface ApplicationSubmitResponse {
  success: boolean;
  data?: {
    applicationId: string;
    applicationNumber: string;
  };
  error?: string;
}

// =====================================================
// API Handler
// =====================================================

export async function POST(request: NextRequest): Promise<NextResponse<ApplicationSubmitResponse>> {
  try {
    const body = await request.json() as ApplicationSubmitRequest;

    // Validate required fields
    if (!body.abn || !body.businessName) {
      return NextResponse.json(
        {
          success: false,
          error: 'Business details are required',
        },
        { status: 400 }
      );
    }

    if (!body.applicantFirstName || !body.applicantLastName || !body.applicantEmail) {
      return NextResponse.json(
        {
          success: false,
          error: 'Applicant details are required',
        },
        { status: 400 }
      );
    }

    // Create application in transaction
    const result = await transaction(async (client) => {
      // 1. Create application record
      //    application_number is auto-generated by DB trigger (MX-YYYYMMDD-XXXX)
      const applicationResult = await client.query(
        `INSERT INTO applications (
          status,
          entity_type,
          finance_product,
          invoice_amount,
          term_months,
          monthly_payment,
          annual_rate,
          abn,
          trading_name,
          business_name,
          business_street_address,
          business_city,
          business_state,
          business_postcode,
          created_by_email
        ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
        RETURNING id, application_number`,
        [
          ApplicationStatus.INCOMPLETE,
          body.entityType || 'sole_trader',
          body.financeProduct || null,
          body.invoiceAmount || null,
          body.termMonths || null,
          body.monthlyPayment || null,
          body.annualRate || null,
          body.abn,
          body.tradingName || null,
          body.businessName,
          body.businessAddress?.street || null,
          body.businessAddress?.city || null,
          body.businessAddress?.state || null,
          body.businessAddress?.postcode || null,
          body.applicantEmail,
        ]
      );

      const applicationId = applicationResult.rows[0].id;
      const applicationNumber = applicationResult.rows[0].application_number;

      // 2. Create contact record for applicant
      const fullName = `${body.applicantFirstName} ${body.applicantLastName}`.trim();
      await client.query(
        `INSERT INTO contacts (
          application_id,
          role,
          is_primary,
          full_name,
          email,
          mobile_number,
          date_of_birth,
          residency_status,
          residential_street_address,
          residential_city,
          residential_state,
          residential_postcode
        ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)`,
        [
          applicationId,
          'primary_applicant',
          true,
          fullName,
          body.applicantEmail,
          body.applicantPhone || null,
          body.applicantDateOfBirth || null,
          body.residencyStatus || null,
          body.residentialAddress?.street || null,
          body.residentialAddress?.city || null,
          body.residentialAddress?.state || null,
          body.residentialAddress?.postcode || null,
        ]
      );

      // 3. Create financial position record
      if (body.assets || body.liabilities) {
        await client.query(
          `INSERT INTO financial_positions (
            application_id,
            home_value,
            investment_property_value,
            cash_at_bank,
            vehicles_value,
            home_contents_value,
            investments_shares_value,
            other_assets_value,
            mortgage_home,
            mortgage_investment,
            vehicle_loan,
            credit_cards,
            other_liabilities
          ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)`,
          [
            applicationId,
            body.assets?.homeValue || 0,
            body.assets?.investmentPropertyValue || 0,
            body.assets?.cashAtBank || 0,
            body.assets?.vehiclesValue || 0,
            body.assets?.homeContentsValue || 0,
            body.assets?.investmentsSharesValue || 0,
            body.assets?.otherAssetsValue || 0,
            body.liabilities?.mortgageHome || 0,
            body.liabilities?.mortgageInvestment || 0,
            body.liabilities?.vehicleLoan || 0,
            body.liabilities?.creditCards || 0,
            body.liabilities?.otherLiabilities || 0,
          ]
        );
      }

      return {
        applicationId,
        applicationNumber,
      };
    });

    // TODO: Send confirmation email
    // TODO: Trigger CRM sync
    // TODO: Create audit log entry

    return NextResponse.json({
      success: true,
      data: result,
    });

  } catch (error) {
    console.error('Application submission error:', error);

    const errorMessage = error instanceof Error
      ? error.message
      : 'Failed to submit application';

    return NextResponse.json(
      {
        success: false,
        error: errorMessage,
      },
      { status: 500 }
    );
  }
}
